//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class KaynaklarTab
    {
        public int kaynak_ID { get; set; }
        public string kaynak_Ad { get; set; }
        public string kaynak_Yazar { get; set; }
        public string kaynak_Yayinci { get; set; }
        public Nullable<int> kaynak_SayfaSayisi { get; set; }
        public Nullable<System.DateTime> kaynak_BasimTarihi { get; set; }
    }
}
