//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullanicilarTab
    {
        public int kullanici_ID { get; set; }
        public string kullanici_Ad { get; set; }
        public string kullanici_Soyad { get; set; }
        public string kullanici_Cinsiyet { get; set; }
        public string kullanici_TC { get; set; }
        public string kullanici_Tel { get; set; }
        public string kullanici_Mail { get; set; }
        public Nullable<double> kullanici_Ceza { get; set; }
    }
}
