//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonellerTab
    {
        public int personel_ID { get; set; }
        public string personel_Ad { get; set; }
        public string personel_Soyad { get; set; }
        public string personel_TC { get; set; }
        public string personel_Tel { get; set; }
        public string personel_Mail { get; set; }
        public string personel_KullaniciAd { get; set; }
        public string personel_Sifre { get; set; }
    }
}
